### ISSUE TITLE
Feature: Ignore URL Patterns

### ISSUE THREAD

**Issue by 1jz** [zg3d/fireLinker#3]
Hey, I want to add a flag `-i`/`--ignore` that passes a file that allows you to ignore certain url patterns. I'll fork your repo and work on it shortly.

**Comment by zg3d** [comment]
Ya, go for it !

**Comment by 1jz** [comment]
Alright, I got around to implementing the feature, you can see it over on on my `ignore-urls` branch [here](https://github.com/1jz/fireLinker/tree/ignore-urls). One thing to note is that I decided to make urls that start with `http://` and `https://` be ignored independently so if a `http://github.com` is in the ignore file `https://github.com` will still be valid vice versa.

Here is a small data set for testing if you'd like:

test_urls:
```
https://www.google.com/index.html
https://www.google.com/
https://www.google.ca
www.google.com
https://youtube.com
https://github.com
http://github.com
```
test_ignore:
```
# 2. File with a comment and single URL that matches any URL
# that starts with https://www.google.com, for example:
#
# https://www.google.com/index.html would match
# https://www.google.com/ would match
# https://www.google.ca would NOT match
https://www.google.com
# This is invalid.  It doesn't use http:// or https://
www.google.com
http://github.com
https://youtube.com
invalid.ca
another invalid line
```

Also, very nice code, it's well written :)

**Comment by zg3d** [comment]
I have merged the change. Thanks for your help!
